# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc201fa13fd7a45adb5f925b3222b7147cfa9ca62c9706db651ff972d87742857e7d4a9198eec035d9eebb41afd52bca02927d9082c3f39b69ab541e0acbe98f

test:
  secret_key_base: 9726e8605ffb5c29a8e858e56f31605645784820ca94cebc97a8d29ce35ba016409369de367653ffa91c2a41b79fb8928efdc500cb13e20380f9831a574f9191

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
